// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/RemoteCommand.proto

// Protobuf Java Version: 3.25.8
package connectedCar;

public final class RemoteCommandProto {
  private RemoteCommandProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RemoteCommandBaseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:connectedCar.RemoteCommandBase)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string vehicle_id = 1;</code>
     * @return The vehicleId.
     */
    java.lang.String getVehicleId();
    /**
     * <code>string vehicle_id = 1;</code>
     * @return The bytes for vehicleId.
     */
    com.google.protobuf.ByteString
        getVehicleIdBytes();

    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code connectedCar.RemoteCommandBase}
   */
  public static final class RemoteCommandBase extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:connectedCar.RemoteCommandBase)
      RemoteCommandBaseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RemoteCommandBase.newBuilder() to construct.
    private RemoteCommandBase(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RemoteCommandBase() {
      vehicleId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RemoteCommandBase();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return connectedCar.RemoteCommandProto.internal_static_connectedCar_RemoteCommandBase_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return connectedCar.RemoteCommandProto.internal_static_connectedCar_RemoteCommandBase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              connectedCar.RemoteCommandProto.RemoteCommandBase.class, connectedCar.RemoteCommandProto.RemoteCommandBase.Builder.class);
    }

    public static final int VEHICLE_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object vehicleId_ = "";
    /**
     * <code>string vehicle_id = 1;</code>
     * @return The vehicleId.
     */
    @java.lang.Override
    public java.lang.String getVehicleId() {
      java.lang.Object ref = vehicleId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vehicleId_ = s;
        return s;
      }
    }
    /**
     * <code>string vehicle_id = 1;</code>
     * @return The bytes for vehicleId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVehicleIdBytes() {
      java.lang.Object ref = vehicleId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vehicleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_ = 0L;
    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vehicleId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, vehicleId_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(2, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vehicleId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, vehicleId_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof connectedCar.RemoteCommandProto.RemoteCommandBase)) {
        return super.equals(obj);
      }
      connectedCar.RemoteCommandProto.RemoteCommandBase other = (connectedCar.RemoteCommandProto.RemoteCommandBase) obj;

      if (!getVehicleId()
          .equals(other.getVehicleId())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VEHICLE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getVehicleId().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static connectedCar.RemoteCommandProto.RemoteCommandBase parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static connectedCar.RemoteCommandProto.RemoteCommandBase parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static connectedCar.RemoteCommandProto.RemoteCommandBase parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static connectedCar.RemoteCommandProto.RemoteCommandBase parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static connectedCar.RemoteCommandProto.RemoteCommandBase parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static connectedCar.RemoteCommandProto.RemoteCommandBase parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static connectedCar.RemoteCommandProto.RemoteCommandBase parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static connectedCar.RemoteCommandProto.RemoteCommandBase parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static connectedCar.RemoteCommandProto.RemoteCommandBase parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static connectedCar.RemoteCommandProto.RemoteCommandBase parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static connectedCar.RemoteCommandProto.RemoteCommandBase parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static connectedCar.RemoteCommandProto.RemoteCommandBase parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(connectedCar.RemoteCommandProto.RemoteCommandBase prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code connectedCar.RemoteCommandBase}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:connectedCar.RemoteCommandBase)
        connectedCar.RemoteCommandProto.RemoteCommandBaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return connectedCar.RemoteCommandProto.internal_static_connectedCar_RemoteCommandBase_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return connectedCar.RemoteCommandProto.internal_static_connectedCar_RemoteCommandBase_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                connectedCar.RemoteCommandProto.RemoteCommandBase.class, connectedCar.RemoteCommandProto.RemoteCommandBase.Builder.class);
      }

      // Construct using connectedCar.RemoteCommandProto.RemoteCommandBase.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        vehicleId_ = "";
        timestamp_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return connectedCar.RemoteCommandProto.internal_static_connectedCar_RemoteCommandBase_descriptor;
      }

      @java.lang.Override
      public connectedCar.RemoteCommandProto.RemoteCommandBase getDefaultInstanceForType() {
        return connectedCar.RemoteCommandProto.RemoteCommandBase.getDefaultInstance();
      }

      @java.lang.Override
      public connectedCar.RemoteCommandProto.RemoteCommandBase build() {
        connectedCar.RemoteCommandProto.RemoteCommandBase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public connectedCar.RemoteCommandProto.RemoteCommandBase buildPartial() {
        connectedCar.RemoteCommandProto.RemoteCommandBase result = new connectedCar.RemoteCommandProto.RemoteCommandBase(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(connectedCar.RemoteCommandProto.RemoteCommandBase result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.vehicleId_ = vehicleId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.timestamp_ = timestamp_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof connectedCar.RemoteCommandProto.RemoteCommandBase) {
          return mergeFrom((connectedCar.RemoteCommandProto.RemoteCommandBase)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(connectedCar.RemoteCommandProto.RemoteCommandBase other) {
        if (other == connectedCar.RemoteCommandProto.RemoteCommandBase.getDefaultInstance()) return this;
        if (!other.getVehicleId().isEmpty()) {
          vehicleId_ = other.vehicleId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                vehicleId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object vehicleId_ = "";
      /**
       * <code>string vehicle_id = 1;</code>
       * @return The vehicleId.
       */
      public java.lang.String getVehicleId() {
        java.lang.Object ref = vehicleId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          vehicleId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string vehicle_id = 1;</code>
       * @return The bytes for vehicleId.
       */
      public com.google.protobuf.ByteString
          getVehicleIdBytes() {
        java.lang.Object ref = vehicleId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vehicleId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string vehicle_id = 1;</code>
       * @param value The vehicleId to set.
       * @return This builder for chaining.
       */
      public Builder setVehicleId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        vehicleId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string vehicle_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVehicleId() {
        vehicleId_ = getDefaultInstance().getVehicleId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string vehicle_id = 1;</code>
       * @param value The bytes for vehicleId to set.
       * @return This builder for chaining.
       */
      public Builder setVehicleIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        vehicleId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 2;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 2;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:connectedCar.RemoteCommandBase)
    }

    // @@protoc_insertion_point(class_scope:connectedCar.RemoteCommandBase)
    private static final connectedCar.RemoteCommandProto.RemoteCommandBase DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new connectedCar.RemoteCommandProto.RemoteCommandBase();
    }

    public static connectedCar.RemoteCommandProto.RemoteCommandBase getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RemoteCommandBase>
        PARSER = new com.google.protobuf.AbstractParser<RemoteCommandBase>() {
      @java.lang.Override
      public RemoteCommandBase parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RemoteCommandBase> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RemoteCommandBase> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public connectedCar.RemoteCommandProto.RemoteCommandBase getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EngineControlOrBuilder extends
      // @@protoc_insertion_point(interface_extends:connectedCar.EngineControl)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool is_start = 1;</code>
     * @return The isStart.
     */
    boolean getIsStart();

    /**
     * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
     * @return Whether the remoteCommandBase field is set.
     */
    boolean hasRemoteCommandBase();
    /**
     * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
     * @return The remoteCommandBase.
     */
    connectedCar.RemoteCommandProto.RemoteCommandBase getRemoteCommandBase();
    /**
     * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
     */
    connectedCar.RemoteCommandProto.RemoteCommandBaseOrBuilder getRemoteCommandBaseOrBuilder();
  }
  /**
   * Protobuf type {@code connectedCar.EngineControl}
   */
  public static final class EngineControl extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:connectedCar.EngineControl)
      EngineControlOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EngineControl.newBuilder() to construct.
    private EngineControl(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EngineControl() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EngineControl();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return connectedCar.RemoteCommandProto.internal_static_connectedCar_EngineControl_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return connectedCar.RemoteCommandProto.internal_static_connectedCar_EngineControl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              connectedCar.RemoteCommandProto.EngineControl.class, connectedCar.RemoteCommandProto.EngineControl.Builder.class);
    }

    private int bitField0_;
    public static final int IS_START_FIELD_NUMBER = 1;
    private boolean isStart_ = false;
    /**
     * <code>bool is_start = 1;</code>
     * @return The isStart.
     */
    @java.lang.Override
    public boolean getIsStart() {
      return isStart_;
    }

    public static final int REMOTECOMMANDBASE_FIELD_NUMBER = 2;
    private connectedCar.RemoteCommandProto.RemoteCommandBase remoteCommandBase_;
    /**
     * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
     * @return Whether the remoteCommandBase field is set.
     */
    @java.lang.Override
    public boolean hasRemoteCommandBase() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
     * @return The remoteCommandBase.
     */
    @java.lang.Override
    public connectedCar.RemoteCommandProto.RemoteCommandBase getRemoteCommandBase() {
      return remoteCommandBase_ == null ? connectedCar.RemoteCommandProto.RemoteCommandBase.getDefaultInstance() : remoteCommandBase_;
    }
    /**
     * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
     */
    @java.lang.Override
    public connectedCar.RemoteCommandProto.RemoteCommandBaseOrBuilder getRemoteCommandBaseOrBuilder() {
      return remoteCommandBase_ == null ? connectedCar.RemoteCommandProto.RemoteCommandBase.getDefaultInstance() : remoteCommandBase_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (isStart_ != false) {
        output.writeBool(1, isStart_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getRemoteCommandBase());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (isStart_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isStart_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRemoteCommandBase());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof connectedCar.RemoteCommandProto.EngineControl)) {
        return super.equals(obj);
      }
      connectedCar.RemoteCommandProto.EngineControl other = (connectedCar.RemoteCommandProto.EngineControl) obj;

      if (getIsStart()
          != other.getIsStart()) return false;
      if (hasRemoteCommandBase() != other.hasRemoteCommandBase()) return false;
      if (hasRemoteCommandBase()) {
        if (!getRemoteCommandBase()
            .equals(other.getRemoteCommandBase())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IS_START_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsStart());
      if (hasRemoteCommandBase()) {
        hash = (37 * hash) + REMOTECOMMANDBASE_FIELD_NUMBER;
        hash = (53 * hash) + getRemoteCommandBase().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static connectedCar.RemoteCommandProto.EngineControl parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static connectedCar.RemoteCommandProto.EngineControl parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static connectedCar.RemoteCommandProto.EngineControl parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static connectedCar.RemoteCommandProto.EngineControl parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static connectedCar.RemoteCommandProto.EngineControl parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static connectedCar.RemoteCommandProto.EngineControl parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static connectedCar.RemoteCommandProto.EngineControl parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static connectedCar.RemoteCommandProto.EngineControl parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static connectedCar.RemoteCommandProto.EngineControl parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static connectedCar.RemoteCommandProto.EngineControl parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static connectedCar.RemoteCommandProto.EngineControl parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static connectedCar.RemoteCommandProto.EngineControl parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(connectedCar.RemoteCommandProto.EngineControl prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code connectedCar.EngineControl}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:connectedCar.EngineControl)
        connectedCar.RemoteCommandProto.EngineControlOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return connectedCar.RemoteCommandProto.internal_static_connectedCar_EngineControl_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return connectedCar.RemoteCommandProto.internal_static_connectedCar_EngineControl_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                connectedCar.RemoteCommandProto.EngineControl.class, connectedCar.RemoteCommandProto.EngineControl.Builder.class);
      }

      // Construct using connectedCar.RemoteCommandProto.EngineControl.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRemoteCommandBaseFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        isStart_ = false;
        remoteCommandBase_ = null;
        if (remoteCommandBaseBuilder_ != null) {
          remoteCommandBaseBuilder_.dispose();
          remoteCommandBaseBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return connectedCar.RemoteCommandProto.internal_static_connectedCar_EngineControl_descriptor;
      }

      @java.lang.Override
      public connectedCar.RemoteCommandProto.EngineControl getDefaultInstanceForType() {
        return connectedCar.RemoteCommandProto.EngineControl.getDefaultInstance();
      }

      @java.lang.Override
      public connectedCar.RemoteCommandProto.EngineControl build() {
        connectedCar.RemoteCommandProto.EngineControl result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public connectedCar.RemoteCommandProto.EngineControl buildPartial() {
        connectedCar.RemoteCommandProto.EngineControl result = new connectedCar.RemoteCommandProto.EngineControl(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(connectedCar.RemoteCommandProto.EngineControl result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.isStart_ = isStart_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.remoteCommandBase_ = remoteCommandBaseBuilder_ == null
              ? remoteCommandBase_
              : remoteCommandBaseBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof connectedCar.RemoteCommandProto.EngineControl) {
          return mergeFrom((connectedCar.RemoteCommandProto.EngineControl)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(connectedCar.RemoteCommandProto.EngineControl other) {
        if (other == connectedCar.RemoteCommandProto.EngineControl.getDefaultInstance()) return this;
        if (other.getIsStart() != false) {
          setIsStart(other.getIsStart());
        }
        if (other.hasRemoteCommandBase()) {
          mergeRemoteCommandBase(other.getRemoteCommandBase());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                isStart_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getRemoteCommandBaseFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean isStart_ ;
      /**
       * <code>bool is_start = 1;</code>
       * @return The isStart.
       */
      @java.lang.Override
      public boolean getIsStart() {
        return isStart_;
      }
      /**
       * <code>bool is_start = 1;</code>
       * @param value The isStart to set.
       * @return This builder for chaining.
       */
      public Builder setIsStart(boolean value) {

        isStart_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_start = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsStart() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isStart_ = false;
        onChanged();
        return this;
      }

      private connectedCar.RemoteCommandProto.RemoteCommandBase remoteCommandBase_;
      private com.google.protobuf.SingleFieldBuilderV3<
          connectedCar.RemoteCommandProto.RemoteCommandBase, connectedCar.RemoteCommandProto.RemoteCommandBase.Builder, connectedCar.RemoteCommandProto.RemoteCommandBaseOrBuilder> remoteCommandBaseBuilder_;
      /**
       * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
       * @return Whether the remoteCommandBase field is set.
       */
      public boolean hasRemoteCommandBase() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
       * @return The remoteCommandBase.
       */
      public connectedCar.RemoteCommandProto.RemoteCommandBase getRemoteCommandBase() {
        if (remoteCommandBaseBuilder_ == null) {
          return remoteCommandBase_ == null ? connectedCar.RemoteCommandProto.RemoteCommandBase.getDefaultInstance() : remoteCommandBase_;
        } else {
          return remoteCommandBaseBuilder_.getMessage();
        }
      }
      /**
       * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
       */
      public Builder setRemoteCommandBase(connectedCar.RemoteCommandProto.RemoteCommandBase value) {
        if (remoteCommandBaseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          remoteCommandBase_ = value;
        } else {
          remoteCommandBaseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
       */
      public Builder setRemoteCommandBase(
          connectedCar.RemoteCommandProto.RemoteCommandBase.Builder builderForValue) {
        if (remoteCommandBaseBuilder_ == null) {
          remoteCommandBase_ = builderForValue.build();
        } else {
          remoteCommandBaseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
       */
      public Builder mergeRemoteCommandBase(connectedCar.RemoteCommandProto.RemoteCommandBase value) {
        if (remoteCommandBaseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            remoteCommandBase_ != null &&
            remoteCommandBase_ != connectedCar.RemoteCommandProto.RemoteCommandBase.getDefaultInstance()) {
            getRemoteCommandBaseBuilder().mergeFrom(value);
          } else {
            remoteCommandBase_ = value;
          }
        } else {
          remoteCommandBaseBuilder_.mergeFrom(value);
        }
        if (remoteCommandBase_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
       */
      public Builder clearRemoteCommandBase() {
        bitField0_ = (bitField0_ & ~0x00000002);
        remoteCommandBase_ = null;
        if (remoteCommandBaseBuilder_ != null) {
          remoteCommandBaseBuilder_.dispose();
          remoteCommandBaseBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
       */
      public connectedCar.RemoteCommandProto.RemoteCommandBase.Builder getRemoteCommandBaseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRemoteCommandBaseFieldBuilder().getBuilder();
      }
      /**
       * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
       */
      public connectedCar.RemoteCommandProto.RemoteCommandBaseOrBuilder getRemoteCommandBaseOrBuilder() {
        if (remoteCommandBaseBuilder_ != null) {
          return remoteCommandBaseBuilder_.getMessageOrBuilder();
        } else {
          return remoteCommandBase_ == null ?
              connectedCar.RemoteCommandProto.RemoteCommandBase.getDefaultInstance() : remoteCommandBase_;
        }
      }
      /**
       * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          connectedCar.RemoteCommandProto.RemoteCommandBase, connectedCar.RemoteCommandProto.RemoteCommandBase.Builder, connectedCar.RemoteCommandProto.RemoteCommandBaseOrBuilder> 
          getRemoteCommandBaseFieldBuilder() {
        if (remoteCommandBaseBuilder_ == null) {
          remoteCommandBaseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              connectedCar.RemoteCommandProto.RemoteCommandBase, connectedCar.RemoteCommandProto.RemoteCommandBase.Builder, connectedCar.RemoteCommandProto.RemoteCommandBaseOrBuilder>(
                  getRemoteCommandBase(),
                  getParentForChildren(),
                  isClean());
          remoteCommandBase_ = null;
        }
        return remoteCommandBaseBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:connectedCar.EngineControl)
    }

    // @@protoc_insertion_point(class_scope:connectedCar.EngineControl)
    private static final connectedCar.RemoteCommandProto.EngineControl DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new connectedCar.RemoteCommandProto.EngineControl();
    }

    public static connectedCar.RemoteCommandProto.EngineControl getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EngineControl>
        PARSER = new com.google.protobuf.AbstractParser<EngineControl>() {
      @java.lang.Override
      public EngineControl parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EngineControl> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EngineControl> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public connectedCar.RemoteCommandProto.EngineControl getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DoorControlOrBuilder extends
      // @@protoc_insertion_point(interface_extends:connectedCar.DoorControl)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool is_lock = 1;</code>
     * @return The isLock.
     */
    boolean getIsLock();

    /**
     * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
     * @return Whether the remoteCommandBase field is set.
     */
    boolean hasRemoteCommandBase();
    /**
     * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
     * @return The remoteCommandBase.
     */
    connectedCar.RemoteCommandProto.RemoteCommandBase getRemoteCommandBase();
    /**
     * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
     */
    connectedCar.RemoteCommandProto.RemoteCommandBaseOrBuilder getRemoteCommandBaseOrBuilder();
  }
  /**
   * Protobuf type {@code connectedCar.DoorControl}
   */
  public static final class DoorControl extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:connectedCar.DoorControl)
      DoorControlOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DoorControl.newBuilder() to construct.
    private DoorControl(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DoorControl() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DoorControl();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return connectedCar.RemoteCommandProto.internal_static_connectedCar_DoorControl_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return connectedCar.RemoteCommandProto.internal_static_connectedCar_DoorControl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              connectedCar.RemoteCommandProto.DoorControl.class, connectedCar.RemoteCommandProto.DoorControl.Builder.class);
    }

    private int bitField0_;
    public static final int IS_LOCK_FIELD_NUMBER = 1;
    private boolean isLock_ = false;
    /**
     * <code>bool is_lock = 1;</code>
     * @return The isLock.
     */
    @java.lang.Override
    public boolean getIsLock() {
      return isLock_;
    }

    public static final int REMOTECOMMANDBASE_FIELD_NUMBER = 2;
    private connectedCar.RemoteCommandProto.RemoteCommandBase remoteCommandBase_;
    /**
     * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
     * @return Whether the remoteCommandBase field is set.
     */
    @java.lang.Override
    public boolean hasRemoteCommandBase() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
     * @return The remoteCommandBase.
     */
    @java.lang.Override
    public connectedCar.RemoteCommandProto.RemoteCommandBase getRemoteCommandBase() {
      return remoteCommandBase_ == null ? connectedCar.RemoteCommandProto.RemoteCommandBase.getDefaultInstance() : remoteCommandBase_;
    }
    /**
     * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
     */
    @java.lang.Override
    public connectedCar.RemoteCommandProto.RemoteCommandBaseOrBuilder getRemoteCommandBaseOrBuilder() {
      return remoteCommandBase_ == null ? connectedCar.RemoteCommandProto.RemoteCommandBase.getDefaultInstance() : remoteCommandBase_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (isLock_ != false) {
        output.writeBool(1, isLock_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getRemoteCommandBase());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (isLock_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isLock_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRemoteCommandBase());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof connectedCar.RemoteCommandProto.DoorControl)) {
        return super.equals(obj);
      }
      connectedCar.RemoteCommandProto.DoorControl other = (connectedCar.RemoteCommandProto.DoorControl) obj;

      if (getIsLock()
          != other.getIsLock()) return false;
      if (hasRemoteCommandBase() != other.hasRemoteCommandBase()) return false;
      if (hasRemoteCommandBase()) {
        if (!getRemoteCommandBase()
            .equals(other.getRemoteCommandBase())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IS_LOCK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsLock());
      if (hasRemoteCommandBase()) {
        hash = (37 * hash) + REMOTECOMMANDBASE_FIELD_NUMBER;
        hash = (53 * hash) + getRemoteCommandBase().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static connectedCar.RemoteCommandProto.DoorControl parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static connectedCar.RemoteCommandProto.DoorControl parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static connectedCar.RemoteCommandProto.DoorControl parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static connectedCar.RemoteCommandProto.DoorControl parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static connectedCar.RemoteCommandProto.DoorControl parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static connectedCar.RemoteCommandProto.DoorControl parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static connectedCar.RemoteCommandProto.DoorControl parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static connectedCar.RemoteCommandProto.DoorControl parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static connectedCar.RemoteCommandProto.DoorControl parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static connectedCar.RemoteCommandProto.DoorControl parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static connectedCar.RemoteCommandProto.DoorControl parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static connectedCar.RemoteCommandProto.DoorControl parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(connectedCar.RemoteCommandProto.DoorControl prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code connectedCar.DoorControl}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:connectedCar.DoorControl)
        connectedCar.RemoteCommandProto.DoorControlOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return connectedCar.RemoteCommandProto.internal_static_connectedCar_DoorControl_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return connectedCar.RemoteCommandProto.internal_static_connectedCar_DoorControl_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                connectedCar.RemoteCommandProto.DoorControl.class, connectedCar.RemoteCommandProto.DoorControl.Builder.class);
      }

      // Construct using connectedCar.RemoteCommandProto.DoorControl.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRemoteCommandBaseFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        isLock_ = false;
        remoteCommandBase_ = null;
        if (remoteCommandBaseBuilder_ != null) {
          remoteCommandBaseBuilder_.dispose();
          remoteCommandBaseBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return connectedCar.RemoteCommandProto.internal_static_connectedCar_DoorControl_descriptor;
      }

      @java.lang.Override
      public connectedCar.RemoteCommandProto.DoorControl getDefaultInstanceForType() {
        return connectedCar.RemoteCommandProto.DoorControl.getDefaultInstance();
      }

      @java.lang.Override
      public connectedCar.RemoteCommandProto.DoorControl build() {
        connectedCar.RemoteCommandProto.DoorControl result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public connectedCar.RemoteCommandProto.DoorControl buildPartial() {
        connectedCar.RemoteCommandProto.DoorControl result = new connectedCar.RemoteCommandProto.DoorControl(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(connectedCar.RemoteCommandProto.DoorControl result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.isLock_ = isLock_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.remoteCommandBase_ = remoteCommandBaseBuilder_ == null
              ? remoteCommandBase_
              : remoteCommandBaseBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof connectedCar.RemoteCommandProto.DoorControl) {
          return mergeFrom((connectedCar.RemoteCommandProto.DoorControl)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(connectedCar.RemoteCommandProto.DoorControl other) {
        if (other == connectedCar.RemoteCommandProto.DoorControl.getDefaultInstance()) return this;
        if (other.getIsLock() != false) {
          setIsLock(other.getIsLock());
        }
        if (other.hasRemoteCommandBase()) {
          mergeRemoteCommandBase(other.getRemoteCommandBase());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                isLock_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getRemoteCommandBaseFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean isLock_ ;
      /**
       * <code>bool is_lock = 1;</code>
       * @return The isLock.
       */
      @java.lang.Override
      public boolean getIsLock() {
        return isLock_;
      }
      /**
       * <code>bool is_lock = 1;</code>
       * @param value The isLock to set.
       * @return This builder for chaining.
       */
      public Builder setIsLock(boolean value) {

        isLock_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_lock = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsLock() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isLock_ = false;
        onChanged();
        return this;
      }

      private connectedCar.RemoteCommandProto.RemoteCommandBase remoteCommandBase_;
      private com.google.protobuf.SingleFieldBuilderV3<
          connectedCar.RemoteCommandProto.RemoteCommandBase, connectedCar.RemoteCommandProto.RemoteCommandBase.Builder, connectedCar.RemoteCommandProto.RemoteCommandBaseOrBuilder> remoteCommandBaseBuilder_;
      /**
       * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
       * @return Whether the remoteCommandBase field is set.
       */
      public boolean hasRemoteCommandBase() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
       * @return The remoteCommandBase.
       */
      public connectedCar.RemoteCommandProto.RemoteCommandBase getRemoteCommandBase() {
        if (remoteCommandBaseBuilder_ == null) {
          return remoteCommandBase_ == null ? connectedCar.RemoteCommandProto.RemoteCommandBase.getDefaultInstance() : remoteCommandBase_;
        } else {
          return remoteCommandBaseBuilder_.getMessage();
        }
      }
      /**
       * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
       */
      public Builder setRemoteCommandBase(connectedCar.RemoteCommandProto.RemoteCommandBase value) {
        if (remoteCommandBaseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          remoteCommandBase_ = value;
        } else {
          remoteCommandBaseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
       */
      public Builder setRemoteCommandBase(
          connectedCar.RemoteCommandProto.RemoteCommandBase.Builder builderForValue) {
        if (remoteCommandBaseBuilder_ == null) {
          remoteCommandBase_ = builderForValue.build();
        } else {
          remoteCommandBaseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
       */
      public Builder mergeRemoteCommandBase(connectedCar.RemoteCommandProto.RemoteCommandBase value) {
        if (remoteCommandBaseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            remoteCommandBase_ != null &&
            remoteCommandBase_ != connectedCar.RemoteCommandProto.RemoteCommandBase.getDefaultInstance()) {
            getRemoteCommandBaseBuilder().mergeFrom(value);
          } else {
            remoteCommandBase_ = value;
          }
        } else {
          remoteCommandBaseBuilder_.mergeFrom(value);
        }
        if (remoteCommandBase_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
       */
      public Builder clearRemoteCommandBase() {
        bitField0_ = (bitField0_ & ~0x00000002);
        remoteCommandBase_ = null;
        if (remoteCommandBaseBuilder_ != null) {
          remoteCommandBaseBuilder_.dispose();
          remoteCommandBaseBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
       */
      public connectedCar.RemoteCommandProto.RemoteCommandBase.Builder getRemoteCommandBaseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRemoteCommandBaseFieldBuilder().getBuilder();
      }
      /**
       * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
       */
      public connectedCar.RemoteCommandProto.RemoteCommandBaseOrBuilder getRemoteCommandBaseOrBuilder() {
        if (remoteCommandBaseBuilder_ != null) {
          return remoteCommandBaseBuilder_.getMessageOrBuilder();
        } else {
          return remoteCommandBase_ == null ?
              connectedCar.RemoteCommandProto.RemoteCommandBase.getDefaultInstance() : remoteCommandBase_;
        }
      }
      /**
       * <code>.connectedCar.RemoteCommandBase remoteCommandBase = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          connectedCar.RemoteCommandProto.RemoteCommandBase, connectedCar.RemoteCommandProto.RemoteCommandBase.Builder, connectedCar.RemoteCommandProto.RemoteCommandBaseOrBuilder> 
          getRemoteCommandBaseFieldBuilder() {
        if (remoteCommandBaseBuilder_ == null) {
          remoteCommandBaseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              connectedCar.RemoteCommandProto.RemoteCommandBase, connectedCar.RemoteCommandProto.RemoteCommandBase.Builder, connectedCar.RemoteCommandProto.RemoteCommandBaseOrBuilder>(
                  getRemoteCommandBase(),
                  getParentForChildren(),
                  isClean());
          remoteCommandBase_ = null;
        }
        return remoteCommandBaseBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:connectedCar.DoorControl)
    }

    // @@protoc_insertion_point(class_scope:connectedCar.DoorControl)
    private static final connectedCar.RemoteCommandProto.DoorControl DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new connectedCar.RemoteCommandProto.DoorControl();
    }

    public static connectedCar.RemoteCommandProto.DoorControl getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DoorControl>
        PARSER = new com.google.protobuf.AbstractParser<DoorControl>() {
      @java.lang.Override
      public DoorControl parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DoorControl> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DoorControl> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public connectedCar.RemoteCommandProto.DoorControl getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connectedCar_RemoteCommandBase_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connectedCar_RemoteCommandBase_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connectedCar_EngineControl_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connectedCar_EngineControl_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connectedCar_DoorControl_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connectedCar_DoorControl_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"src/main/proto/RemoteCommand.proto\022\014co" +
      "nnectedCar\":\n\021RemoteCommandBase\022\022\n\nvehic" +
      "le_id\030\001 \001(\t\022\021\n\ttimestamp\030\002 \001(\003\"]\n\rEngine" +
      "Control\022\020\n\010is_start\030\001 \001(\010\022:\n\021remoteComma" +
      "ndBase\030\002 \001(\0132\037.connectedCar.RemoteComman" +
      "dBase\"Z\n\013DoorControl\022\017\n\007is_lock\030\001 \001(\010\022:\n" +
      "\021remoteCommandBase\030\002 \001(\0132\037.connectedCar." +
      "RemoteCommandBaseB\024B\022RemoteCommandProtob" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_connectedCar_RemoteCommandBase_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_connectedCar_RemoteCommandBase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connectedCar_RemoteCommandBase_descriptor,
        new java.lang.String[] { "VehicleId", "Timestamp", });
    internal_static_connectedCar_EngineControl_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_connectedCar_EngineControl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connectedCar_EngineControl_descriptor,
        new java.lang.String[] { "IsStart", "RemoteCommandBase", });
    internal_static_connectedCar_DoorControl_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_connectedCar_DoorControl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connectedCar_DoorControl_descriptor,
        new java.lang.String[] { "IsLock", "RemoteCommandBase", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
