// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/protoTest.proto

// Protobuf Java Version: 3.25.8
package proto;

public interface NewOrBuilder extends
    // @@protoc_insertion_point(interface_extends:New)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 birth = 2;</code>
   * @return The birth.
   */
  int getBirth();
}
