// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/protoTest.proto

// Protobuf Java Version: 3.25.8
package proto;

public final class ProtoTest {
  private ProtoTest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Old_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Old_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_New_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_New_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036src/main/proto/protoTest.proto\" \n\003Old\022" +
      "\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\"\"\n\003New\022\014\n\004nam" +
      "e\030\001 \001(\t\022\r\n\005birth\030\002 \001(\005B\t\n\005protoP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Old_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Old_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Old_descriptor,
        new java.lang.String[] { "Name", "Age", });
    internal_static_New_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_New_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_New_descriptor,
        new java.lang.String[] { "Name", "Birth", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
