// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/test.proto

// Protobuf Java Version: 3.25.8
package proto;

public interface TestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Test)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string one = 1;</code>
   * @return The one.
   */
  java.lang.String getOne();
  /**
   * <code>string one = 1;</code>
   * @return The bytes for one.
   */
  com.google.protobuf.ByteString
      getOneBytes();

  /**
   * <code>string two = 2;</code>
   * @return The two.
   */
  java.lang.String getTwo();
  /**
   * <code>string two = 2;</code>
   * @return The bytes for two.
   */
  com.google.protobuf.ByteString
      getTwoBytes();

  /**
   * <code>string three = 3;</code>
   * @return The three.
   */
  java.lang.String getThree();
  /**
   * <code>string three = 3;</code>
   * @return The bytes for three.
   */
  com.google.protobuf.ByteString
      getThreeBytes();

  /**
   * <code>string four = 4;</code>
   * @return The four.
   */
  java.lang.String getFour();
  /**
   * <code>string four = 4;</code>
   * @return The bytes for four.
   */
  com.google.protobuf.ByteString
      getFourBytes();

  /**
   * <code>string five = 5;</code>
   * @return The five.
   */
  java.lang.String getFive();
  /**
   * <code>string five = 5;</code>
   * @return The bytes for five.
   */
  com.google.protobuf.ByteString
      getFiveBytes();

  /**
   * <code>string six = 6;</code>
   * @return The six.
   */
  java.lang.String getSix();
  /**
   * <code>string six = 6;</code>
   * @return The bytes for six.
   */
  com.google.protobuf.ByteString
      getSixBytes();

  /**
   * <code>string seven = 7;</code>
   * @return The seven.
   */
  java.lang.String getSeven();
  /**
   * <code>string seven = 7;</code>
   * @return The bytes for seven.
   */
  com.google.protobuf.ByteString
      getSevenBytes();

  /**
   * <code>string eight = 8;</code>
   * @return The eight.
   */
  java.lang.String getEight();
  /**
   * <code>string eight = 8;</code>
   * @return The bytes for eight.
   */
  com.google.protobuf.ByteString
      getEightBytes();

  /**
   * <code>string nine = 9;</code>
   * @return The nine.
   */
  java.lang.String getNine();
  /**
   * <code>string nine = 9;</code>
   * @return The bytes for nine.
   */
  com.google.protobuf.ByteString
      getNineBytes();

  /**
   * <code>string ten = 10;</code>
   * @return The ten.
   */
  java.lang.String getTen();
  /**
   * <code>string ten = 10;</code>
   * @return The bytes for ten.
   */
  com.google.protobuf.ByteString
      getTenBytes();
}
