// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/test.proto

// Protobuf Java Version: 3.25.8
package proto;

/**
 * Protobuf type {@code Test}
 */
public final class Test extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Test)
    TestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Test.newBuilder() to construct.
  private Test(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Test() {
    one_ = "";
    two_ = "";
    three_ = "";
    four_ = "";
    five_ = "";
    six_ = "";
    seven_ = "";
    eight_ = "";
    nine_ = "";
    ten_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Test();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.TestOuterClass.internal_static_Test_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.TestOuterClass.internal_static_Test_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.Test.class, proto.Test.Builder.class);
  }

  public static final int ONE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object one_ = "";
  /**
   * <code>string one = 1;</code>
   * @return The one.
   */
  @java.lang.Override
  public java.lang.String getOne() {
    java.lang.Object ref = one_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      one_ = s;
      return s;
    }
  }
  /**
   * <code>string one = 1;</code>
   * @return The bytes for one.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOneBytes() {
    java.lang.Object ref = one_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      one_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TWO_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object two_ = "";
  /**
   * <code>string two = 2;</code>
   * @return The two.
   */
  @java.lang.Override
  public java.lang.String getTwo() {
    java.lang.Object ref = two_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      two_ = s;
      return s;
    }
  }
  /**
   * <code>string two = 2;</code>
   * @return The bytes for two.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTwoBytes() {
    java.lang.Object ref = two_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      two_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int THREE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object three_ = "";
  /**
   * <code>string three = 3;</code>
   * @return The three.
   */
  @java.lang.Override
  public java.lang.String getThree() {
    java.lang.Object ref = three_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      three_ = s;
      return s;
    }
  }
  /**
   * <code>string three = 3;</code>
   * @return The bytes for three.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getThreeBytes() {
    java.lang.Object ref = three_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      three_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FOUR_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object four_ = "";
  /**
   * <code>string four = 4;</code>
   * @return The four.
   */
  @java.lang.Override
  public java.lang.String getFour() {
    java.lang.Object ref = four_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      four_ = s;
      return s;
    }
  }
  /**
   * <code>string four = 4;</code>
   * @return The bytes for four.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFourBytes() {
    java.lang.Object ref = four_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      four_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIVE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object five_ = "";
  /**
   * <code>string five = 5;</code>
   * @return The five.
   */
  @java.lang.Override
  public java.lang.String getFive() {
    java.lang.Object ref = five_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      five_ = s;
      return s;
    }
  }
  /**
   * <code>string five = 5;</code>
   * @return The bytes for five.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFiveBytes() {
    java.lang.Object ref = five_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      five_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIX_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object six_ = "";
  /**
   * <code>string six = 6;</code>
   * @return The six.
   */
  @java.lang.Override
  public java.lang.String getSix() {
    java.lang.Object ref = six_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      six_ = s;
      return s;
    }
  }
  /**
   * <code>string six = 6;</code>
   * @return The bytes for six.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSixBytes() {
    java.lang.Object ref = six_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      six_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEVEN_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object seven_ = "";
  /**
   * <code>string seven = 7;</code>
   * @return The seven.
   */
  @java.lang.Override
  public java.lang.String getSeven() {
    java.lang.Object ref = seven_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      seven_ = s;
      return s;
    }
  }
  /**
   * <code>string seven = 7;</code>
   * @return The bytes for seven.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSevenBytes() {
    java.lang.Object ref = seven_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      seven_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EIGHT_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eight_ = "";
  /**
   * <code>string eight = 8;</code>
   * @return The eight.
   */
  @java.lang.Override
  public java.lang.String getEight() {
    java.lang.Object ref = eight_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eight_ = s;
      return s;
    }
  }
  /**
   * <code>string eight = 8;</code>
   * @return The bytes for eight.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEightBytes() {
    java.lang.Object ref = eight_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eight_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NINE_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nine_ = "";
  /**
   * <code>string nine = 9;</code>
   * @return The nine.
   */
  @java.lang.Override
  public java.lang.String getNine() {
    java.lang.Object ref = nine_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nine_ = s;
      return s;
    }
  }
  /**
   * <code>string nine = 9;</code>
   * @return The bytes for nine.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNineBytes() {
    java.lang.Object ref = nine_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nine_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEN_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ten_ = "";
  /**
   * <code>string ten = 10;</code>
   * @return The ten.
   */
  @java.lang.Override
  public java.lang.String getTen() {
    java.lang.Object ref = ten_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ten_ = s;
      return s;
    }
  }
  /**
   * <code>string ten = 10;</code>
   * @return The bytes for ten.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenBytes() {
    java.lang.Object ref = ten_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ten_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(one_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, one_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(two_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, two_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(three_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, three_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(four_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, four_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(five_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, five_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(six_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, six_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(seven_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, seven_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eight_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, eight_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nine_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, nine_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ten_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, ten_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(one_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, one_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(two_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, two_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(three_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, three_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(four_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, four_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(five_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, five_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(six_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, six_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(seven_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, seven_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eight_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, eight_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nine_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, nine_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ten_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, ten_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.Test)) {
      return super.equals(obj);
    }
    proto.Test other = (proto.Test) obj;

    if (!getOne()
        .equals(other.getOne())) return false;
    if (!getTwo()
        .equals(other.getTwo())) return false;
    if (!getThree()
        .equals(other.getThree())) return false;
    if (!getFour()
        .equals(other.getFour())) return false;
    if (!getFive()
        .equals(other.getFive())) return false;
    if (!getSix()
        .equals(other.getSix())) return false;
    if (!getSeven()
        .equals(other.getSeven())) return false;
    if (!getEight()
        .equals(other.getEight())) return false;
    if (!getNine()
        .equals(other.getNine())) return false;
    if (!getTen()
        .equals(other.getTen())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ONE_FIELD_NUMBER;
    hash = (53 * hash) + getOne().hashCode();
    hash = (37 * hash) + TWO_FIELD_NUMBER;
    hash = (53 * hash) + getTwo().hashCode();
    hash = (37 * hash) + THREE_FIELD_NUMBER;
    hash = (53 * hash) + getThree().hashCode();
    hash = (37 * hash) + FOUR_FIELD_NUMBER;
    hash = (53 * hash) + getFour().hashCode();
    hash = (37 * hash) + FIVE_FIELD_NUMBER;
    hash = (53 * hash) + getFive().hashCode();
    hash = (37 * hash) + SIX_FIELD_NUMBER;
    hash = (53 * hash) + getSix().hashCode();
    hash = (37 * hash) + SEVEN_FIELD_NUMBER;
    hash = (53 * hash) + getSeven().hashCode();
    hash = (37 * hash) + EIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getEight().hashCode();
    hash = (37 * hash) + NINE_FIELD_NUMBER;
    hash = (53 * hash) + getNine().hashCode();
    hash = (37 * hash) + TEN_FIELD_NUMBER;
    hash = (53 * hash) + getTen().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.Test parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.Test parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.Test parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.Test parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.Test parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.Test parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.Test parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.Test parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static proto.Test parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static proto.Test parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.Test parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.Test parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.Test prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Test}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Test)
      proto.TestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.TestOuterClass.internal_static_Test_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.TestOuterClass.internal_static_Test_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Test.class, proto.Test.Builder.class);
    }

    // Construct using proto.Test.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      one_ = "";
      two_ = "";
      three_ = "";
      four_ = "";
      five_ = "";
      six_ = "";
      seven_ = "";
      eight_ = "";
      nine_ = "";
      ten_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.TestOuterClass.internal_static_Test_descriptor;
    }

    @java.lang.Override
    public proto.Test getDefaultInstanceForType() {
      return proto.Test.getDefaultInstance();
    }

    @java.lang.Override
    public proto.Test build() {
      proto.Test result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.Test buildPartial() {
      proto.Test result = new proto.Test(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(proto.Test result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.one_ = one_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.two_ = two_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.three_ = three_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.four_ = four_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.five_ = five_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.six_ = six_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.seven_ = seven_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.eight_ = eight_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.nine_ = nine_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.ten_ = ten_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.Test) {
        return mergeFrom((proto.Test)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.Test other) {
      if (other == proto.Test.getDefaultInstance()) return this;
      if (!other.getOne().isEmpty()) {
        one_ = other.one_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTwo().isEmpty()) {
        two_ = other.two_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getThree().isEmpty()) {
        three_ = other.three_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getFour().isEmpty()) {
        four_ = other.four_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getFive().isEmpty()) {
        five_ = other.five_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getSix().isEmpty()) {
        six_ = other.six_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getSeven().isEmpty()) {
        seven_ = other.seven_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getEight().isEmpty()) {
        eight_ = other.eight_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getNine().isEmpty()) {
        nine_ = other.nine_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getTen().isEmpty()) {
        ten_ = other.ten_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              one_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              two_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              three_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              four_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              five_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              six_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              seven_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              eight_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              nine_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              ten_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object one_ = "";
    /**
     * <code>string one = 1;</code>
     * @return The one.
     */
    public java.lang.String getOne() {
      java.lang.Object ref = one_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        one_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string one = 1;</code>
     * @return The bytes for one.
     */
    public com.google.protobuf.ByteString
        getOneBytes() {
      java.lang.Object ref = one_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        one_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string one = 1;</code>
     * @param value The one to set.
     * @return This builder for chaining.
     */
    public Builder setOne(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      one_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string one = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOne() {
      one_ = getDefaultInstance().getOne();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string one = 1;</code>
     * @param value The bytes for one to set.
     * @return This builder for chaining.
     */
    public Builder setOneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      one_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object two_ = "";
    /**
     * <code>string two = 2;</code>
     * @return The two.
     */
    public java.lang.String getTwo() {
      java.lang.Object ref = two_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        two_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string two = 2;</code>
     * @return The bytes for two.
     */
    public com.google.protobuf.ByteString
        getTwoBytes() {
      java.lang.Object ref = two_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        two_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string two = 2;</code>
     * @param value The two to set.
     * @return This builder for chaining.
     */
    public Builder setTwo(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      two_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string two = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTwo() {
      two_ = getDefaultInstance().getTwo();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string two = 2;</code>
     * @param value The bytes for two to set.
     * @return This builder for chaining.
     */
    public Builder setTwoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      two_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object three_ = "";
    /**
     * <code>string three = 3;</code>
     * @return The three.
     */
    public java.lang.String getThree() {
      java.lang.Object ref = three_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        three_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string three = 3;</code>
     * @return The bytes for three.
     */
    public com.google.protobuf.ByteString
        getThreeBytes() {
      java.lang.Object ref = three_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        three_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string three = 3;</code>
     * @param value The three to set.
     * @return This builder for chaining.
     */
    public Builder setThree(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      three_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string three = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearThree() {
      three_ = getDefaultInstance().getThree();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string three = 3;</code>
     * @param value The bytes for three to set.
     * @return This builder for chaining.
     */
    public Builder setThreeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      three_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object four_ = "";
    /**
     * <code>string four = 4;</code>
     * @return The four.
     */
    public java.lang.String getFour() {
      java.lang.Object ref = four_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        four_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string four = 4;</code>
     * @return The bytes for four.
     */
    public com.google.protobuf.ByteString
        getFourBytes() {
      java.lang.Object ref = four_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        four_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string four = 4;</code>
     * @param value The four to set.
     * @return This builder for chaining.
     */
    public Builder setFour(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      four_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string four = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFour() {
      four_ = getDefaultInstance().getFour();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string four = 4;</code>
     * @param value The bytes for four to set.
     * @return This builder for chaining.
     */
    public Builder setFourBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      four_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object five_ = "";
    /**
     * <code>string five = 5;</code>
     * @return The five.
     */
    public java.lang.String getFive() {
      java.lang.Object ref = five_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        five_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string five = 5;</code>
     * @return The bytes for five.
     */
    public com.google.protobuf.ByteString
        getFiveBytes() {
      java.lang.Object ref = five_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        five_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string five = 5;</code>
     * @param value The five to set.
     * @return This builder for chaining.
     */
    public Builder setFive(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      five_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string five = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFive() {
      five_ = getDefaultInstance().getFive();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string five = 5;</code>
     * @param value The bytes for five to set.
     * @return This builder for chaining.
     */
    public Builder setFiveBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      five_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object six_ = "";
    /**
     * <code>string six = 6;</code>
     * @return The six.
     */
    public java.lang.String getSix() {
      java.lang.Object ref = six_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        six_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string six = 6;</code>
     * @return The bytes for six.
     */
    public com.google.protobuf.ByteString
        getSixBytes() {
      java.lang.Object ref = six_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        six_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string six = 6;</code>
     * @param value The six to set.
     * @return This builder for chaining.
     */
    public Builder setSix(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      six_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string six = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSix() {
      six_ = getDefaultInstance().getSix();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string six = 6;</code>
     * @param value The bytes for six to set.
     * @return This builder for chaining.
     */
    public Builder setSixBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      six_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object seven_ = "";
    /**
     * <code>string seven = 7;</code>
     * @return The seven.
     */
    public java.lang.String getSeven() {
      java.lang.Object ref = seven_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        seven_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string seven = 7;</code>
     * @return The bytes for seven.
     */
    public com.google.protobuf.ByteString
        getSevenBytes() {
      java.lang.Object ref = seven_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        seven_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string seven = 7;</code>
     * @param value The seven to set.
     * @return This builder for chaining.
     */
    public Builder setSeven(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      seven_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string seven = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeven() {
      seven_ = getDefaultInstance().getSeven();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string seven = 7;</code>
     * @param value The bytes for seven to set.
     * @return This builder for chaining.
     */
    public Builder setSevenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      seven_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object eight_ = "";
    /**
     * <code>string eight = 8;</code>
     * @return The eight.
     */
    public java.lang.String getEight() {
      java.lang.Object ref = eight_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eight_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string eight = 8;</code>
     * @return The bytes for eight.
     */
    public com.google.protobuf.ByteString
        getEightBytes() {
      java.lang.Object ref = eight_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eight_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string eight = 8;</code>
     * @param value The eight to set.
     * @return This builder for chaining.
     */
    public Builder setEight(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eight_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string eight = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearEight() {
      eight_ = getDefaultInstance().getEight();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string eight = 8;</code>
     * @param value The bytes for eight to set.
     * @return This builder for chaining.
     */
    public Builder setEightBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eight_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object nine_ = "";
    /**
     * <code>string nine = 9;</code>
     * @return The nine.
     */
    public java.lang.String getNine() {
      java.lang.Object ref = nine_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nine_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nine = 9;</code>
     * @return The bytes for nine.
     */
    public com.google.protobuf.ByteString
        getNineBytes() {
      java.lang.Object ref = nine_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nine_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nine = 9;</code>
     * @param value The nine to set.
     * @return This builder for chaining.
     */
    public Builder setNine(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nine_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string nine = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearNine() {
      nine_ = getDefaultInstance().getNine();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string nine = 9;</code>
     * @param value The bytes for nine to set.
     * @return This builder for chaining.
     */
    public Builder setNineBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nine_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object ten_ = "";
    /**
     * <code>string ten = 10;</code>
     * @return The ten.
     */
    public java.lang.String getTen() {
      java.lang.Object ref = ten_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ten_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ten = 10;</code>
     * @return The bytes for ten.
     */
    public com.google.protobuf.ByteString
        getTenBytes() {
      java.lang.Object ref = ten_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ten_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ten = 10;</code>
     * @param value The ten to set.
     * @return This builder for chaining.
     */
    public Builder setTen(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ten_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string ten = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearTen() {
      ten_ = getDefaultInstance().getTen();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string ten = 10;</code>
     * @param value The bytes for ten to set.
     * @return This builder for chaining.
     */
    public Builder setTenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ten_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Test)
  }

  // @@protoc_insertion_point(class_scope:Test)
  private static final proto.Test DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.Test();
  }

  public static proto.Test getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Test>
      PARSER = new com.google.protobuf.AbstractParser<Test>() {
    @java.lang.Override
    public Test parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Test> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Test> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.Test getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

